global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node_app"
    static_configs:
      - targets: ["node-app:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
