apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: portfolio
data:
  MONGO_URL: "mongodb://mongodb-service:27017/portfolioDB"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: portfolio
data:
  PORT: "3001"
  AUTH_SERVICE_URL: "http://auth-service:3001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-service-config
  namespace: portfolio
data:
  PORT: "3002"
  AUTH_SERVICE_URL: "http://auth-service:3001"
